In [3]:
from qutip import *


In [4]:
import numpy as np

import matplotlib.pyplot as plt

In [5]:
print(Qobj())

Quantum object: dims=[[1], [1]], shape=(1, 1), type='scalar', dtype=Dense
Qobj data =
[[nan]]


empty obj

ye jo hain vo baat ki ksie row and column matrix create krein

In [6]:
from qutip import *

# 1. Ket
psi = Qobj([[1],
            [0],
            [1]])

# 2. Bra
phi = Qobj([[2, 3, 4]])

# 3. Operator
A = Qobj([[0, 1],
          [1, 0]])

# Print all objects
print("Ket:")
print(psi)

print("\nBra:")
print(phi)

print("\nOperator:")
print(A)

Ket:
Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [1.]]

Bra:
Quantum object: dims=[[1], [3]], shape=(1, 3), type='bra', dtype=Dense
Qobj data =
[[2. 3. 4.]]

Operator:
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 1.]
 [1. 0.]]


In [22]:
from qutip import *

a = destroy(3)

print(a)
a.data

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]


Dia(shape=(3, 3), num_diag=1)

destroy ke ander jitne basis select krieg vahan tak bassi state reduced hogi  htis is also sparse amtric

In [17]:
sigmaz()

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

yahan ep satndr matrix kasie presen tkrein 

In [18]:
from qutip import *

print(basis(5,3))

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]


basis jo hmm numer 3 se bassi satte select kret hain to asal me coutign 0 se begin hotin hain is liye 4th basis selct ho rhiii hain aur ayhan basis stanadr hain

In [19]:
from qutip import *

psi = coherent(5, 0.5)

print(psi)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.88249693]
 [0.44124785]
 [0.15601245]
 [0.04496584]
 [0.01173405]]


yahan pehil 5 fock states ki problity coefficnet diya ja rha hain

In [21]:
jmat(1/2,'+')

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[0. 1.]
 [0. 0.]]

In [23]:
q = destroy(4)

In [24]:
q.data

Dia(shape=(4, 4), num_diag=1)

In [25]:
q.shape

(4, 4)

In [26]:
q.dims

[[4], [4]]

In [27]:
q.type

'oper'

In [28]:
q.isherm

False

A=A† if yes then true if not then false will come

In [29]:
q+5

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dia, isherm=False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

A+5=A+5I  ye bas normal addition ahin

In [30]:
x=sigmax()

x*x

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

simple matrix ka do baar multioply hoan ahain

In [31]:
q**3

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

ye 3 baar bas matrix ko multiply krta ahin

In [32]:
x/np.sqrt(2)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

ye normal square root fucniton hain

In [ ]:
q*x          # here it will tells us that they are incomaptibelsm  Incompatible Qobj shapes  due to matrix size

ye dagger bas adjoint matrix ka kam krta hain  A†=(A∗)

In [35]:
basis(5,3).dag()

Quantum object: dims=[[1], [5]], shape=(1, 5), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 1. 0.]]

In [39]:
coherent_dm(5,1)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]


Ye sirf diagonal values return karta h   yani ki diagonal elemnst ko exxtract krta hain

In [40]:
coherent_dm(5,1).diag

<bound method Qobj.diag of Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]>

In [41]:
coherent_dm(5,1).full()

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

it creates matrix in form of array

In [42]:
coherent_dm(5,1).norm()

1.0

Properly normalized. noet ye normialeizatio check nhi krat hain bas Mathematically
 
norm=∥ψ∥ check krat  Yahan sirf norm calculate kar raha hai, normalize nahi.

In [ ]:
from qutip import *

psi = Qobj([[3],
            [4]])                     #ye exmaple dikhaat hain

print(psi.norm())

5.0


In [44]:
psi = Qobj([[3],
            [4]])

print(psi.unit())

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.6]
 [0.8]]


ye sirf normlazia factor se divide kr deta hain ajsie ki 5 se yani ye ksis bhee martrix ko normlaize kr deta ahin

In [51]:
rho=sigmaz()
rho

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [52]:
rho.sqrtm()

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]

for finding the digainl sumof the matrix

In [53]:
rho.tr()

0.0

In [54]:
(basis(4,2)+basis(4,1)).unit()

Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

In [56]:
x.eigenenergies()

array([-1.,  1.])

In [57]:
x.eigenstates()

(array([-1.,  1.]),
 array([Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
        Qobj data =
        [[-0.70710678]
         [ 0.70710678]]                                                       ,
        Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
        Qobj data =
        [[0.70710678]
         [0.70710678]]                                                        ],
       dtype=object))