In [3]:
from qutip import *

In [11]:
vac = basis(5,0)  #here we are creating 5 basis out f which we selecting frist basis

print(vac)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
a = destroy(5)     #already stiduien

print(a)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]


creating this matrix

In [12]:
print(a*vac)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [13]:
print(a.dag()*vac)


Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]


Vacuum

↓

Add one photon

↓

One-photon state

In [14]:
a.dag()


Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.        ]
 [0.         0.         0.         2.         0.        ]]

In [ ]:
create()
a.dag()

these both represent sam eoperation that si the creation of the state 
create=a†

In [ ]:
c=create(5)   #here it creates the matrix that is 

print(c*vac)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]


In [17]:
c=create(5)  
print(c)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.        ]
 [0.         0.         0.         2.         0.        ]]


In [ ]:
print(c*c*vac)    #vac = basis(5,0)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]


In [22]:
c=create(5)    #incrase the  phtno number

a=destroy(5)   # destroy the matrix  

vac=basis(5,0)  #  ek state generate kiya ja rha hain

print(c*a*vac)      # NUMEBR OPEARTOR APPLY KIYA JA RHA HAIN

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Exactly

a†a∣0⟩   this is liking applying the operaot  (c * a * vac)

Example 2 : c * a * (c * vac)   whats c is here taht si pur creation operot

In [ ]:
print(c*a*(c*vac))   #simple ehre we are leamring hwo to apply numebr operaotr

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]


c**2 * vac  it means we are applying the operaor two times

In [ ]:
print(c**2*vac)
print(c*a*(c**2*vac))

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]


In [25]:
(c**2*vac).unit()

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]

thsi is the normailzd state

In [26]:
c*a*((c**2*vac).unit())

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]

thsi is the normlized state....Why .unit() ? so thsisi use becasue we want to normalize thisngs

In [27]:
n=num(5)

print(n)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


thsi is for the eiegn values which coorespod the numebr fo photon..

In [28]:
ket=basis(5,2)

print(n*ket)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]


In [30]:
ket=(basis(5,0)+basis(5,1)).unit()
print(ket)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]


print(n*ket)

In [ ]:
print(n*ket)  # here it actually summing the coefficit avlues what  will happend if we sue normlaized satte

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]


DENSITY MATRIX......

In [ ]:
ket = basis(5,2)
rho = ket * ket.dag()    # ket.dag() here thsi is not annihilatio operaotr it si simple making conjugate of the state
print(rho)                #note here we will get excatly 3rd basis which we need 

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
ket = basis(5,2)

rho = ket2dm(ket)     #ket2dm=ket * ket.dag()  we are just using direct fucniton 

print(rho)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
fock_dm(5,2)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

∣2⟩⟨2∣=
​00100​
​[0​0​1​0​0​]             

Part 4 : fock_dm()
Physics ->Directly create -> Density matrix ->without creating ket.  so int hsi codde we are directly creatign density matrix

In [37]:
0.5*ket2dm(basis(5,2)) +0.5*ket2dm(basis(5,4))

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]

In [ ]:
thsi si telling us that 3rd staet mensas bassi and 5th absis are the in superosito state

In [38]:
psi = (basis(5,2) + basis(5,4)).unit()

rho = ket2dm(psi)

print(rho)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.5]]


In [39]:
rho = 0.5*ket2dm(basis(5,2)) + 0.5*ket2dm(basis(5,4))

print(rho)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]


i am not able to differiae these two result whats going on hehre....???

In [ ]:
coherent_dm(5,1.25)             #thsi we cna sue fro the mix state of the coherent state 

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.20980701 0.26141096 0.23509686 0.15572585 0.13390765]
 [0.26141096 0.32570738 0.29292109 0.19402805 0.16684347]
 [0.23509686 0.29292109 0.26343512 0.17449684 0.1500487 ]
 [0.15572585 0.19402805 0.17449684 0.11558499 0.09939079]
 [0.13390765 0.16684347 0.1500487  0.09939079 0.0854655 ]]

note here we are gettign non zero allot elemnsts ebcasue u can see expansion of the alpha satte

In [41]:
thermal_dm(5,1.25)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0.46927974 0.         0.         0.         0.        ]
 [0.         0.26071096 0.         0.         0.        ]
 [0.         0.         0.14483942 0.         0.        ]
 [0.         0.         0.         0.08046635 0.        ]
 [0.         0.         0.         0.         0.04470353]]

it si fro the bulb,light,tubelight phton numebr countign it telling us the proablity of each sphtotn numebr state 

TRY TO DEEPLY ANANLYSE OUTPUT OF THESE MATRIX HOW OT INTERECEPT

In [42]:
psi = basis(2,0)

phi = basis(2,0)
fidelity(psi,phi)

np.float64(1.0)

Think of fidelity as a similarity score.  as the inner product...

Humne Fidelity me poocha tha

"Ye dono states kitni similar hain?"

Trace Distance ulta question poochta hai:

"Ye dono states kitni different hain?"

Yaani

Fidelity = Similarity
Trace Distance = Difference

In [43]:
psi = basis(2,0)

tracedist(psi,psi)

np.float64(0.0)

In [44]:
rho = coherent_dm(5,1.25)

sigma = thermal_dm(5,1.25)

tracedist(rho,sigma)

np.float64(0.7836362670098136)

actaully ayahn ep ey doiah rha ahin ki do coherenrt state em kitni differenc  ahin 

TWO LEVEL SYSTEM

In [46]:
c = create(2)
print(c)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0. 0.]
 [1. 0.]]


thsi is your  Ye creation operator hai  for two level sytem..

In [48]:
spin = basis(2,0)
sigmaz()*spin

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

simple here we are applying sogma z opearor

In [ ]:
expect(operator,state)
expect(A,psi)                     #this is the way to expressed for the exceptation value

In [51]:
vac = basis(5,0)

N = num(5)

expect(N,vac)

0.0

⟨0∣N∣0⟩=0    Vacuum state me kitne photons hain?

In [ ]:
one = basis(5,1)

expect(N,one)      #thsis si the simpel way to find the qauntum numebr in particualr absis

1.0

In [ ]:
coh = coherent_dm(5,1j)    #here 1j is the imaginery iota value

expect(N,coh)

0.9970555745806597

see here we are gettign excat expecation value....expect use thhhis fucntion to fidn the value

In [ ]:
coherent_dm(50,1j)   #understand output...

Quantum object: dims=[[50], [50]], shape=(50, 50), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.36787944+0.j          0.        -0.36787944j -0.26013005-0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.36787944j  0.36787944+0.j          0.        -0.26013005j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [-0.26013005+0.j          0.        +0.26013005j  0.18393972+0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 ...
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]]

yani ki non diogoanl system ye bata rha ahin ki inetrference between system ....aur diogoanl system inki her satte ki proablut ko edxpalin kr rha hain also above amttrix is the hermittion

In [ ]:
state=[(c**k*vac).unit()
for k in range(5)]
expect(N,state)

In [ ]:
up=basis(2,0)

expect(sigmaz(),up)    #notw here we are describing the spin one state corresponding that we excepataiton vlaue s....



-1.0

In [59]:
down=basis(2,1)

expect(sigmaz(),down)

-1.0

here si the samen process we are doing

In [62]:
spin1=basis(2,0)

spin2=basis(2,1)

two_spins=tensor(spin1,spin2)
sz1=tensor(sigmaz(),qeye(2))
print(sz1)

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]


In [63]:
sz2=tensor(qeye(2),sigmaz())